# %%
"""
# Day 5 — Section 4: Image Watermarking in Diffusion Models

<!-- toc -->

Now we explore a different security aspect: embedding invisible watermarks in AI-generated images using
frequency-domain manipulation of the diffusion UNet's intermediate outputs.

## Content & Learning Objectives

### Image Watermarking in Diffusion Models
We'll learn to hide information in images generated by Stable Diffusion using frequency-domain manipulation.

> **Learning Objectives**
> - Understand frequency-domain representation of images (FFT)
> - Hook into a diffusion model's UNet forward pass to modify outputs
> - Implement and analyze frequency-band watermarking
> - Test watermark robustness against common image transformations
"""

import sys
from pathlib import Path

_root = next(p for p in Path(__file__).resolve().parents if (p / "aisb_utils").is_dir())
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from aisb_utils import report

# %%
"""
## Setup

Create a file named `section4_answers.py` in the `5.4-watermarking` directory. This will be your answer file for this
section.

If you see a code snippet here in the instruction file, copy-paste it into your answer file. Keep the `# %%` line to
make it a Python code cell.

**Start by pasting the code below in your section4_answers.py file.**
"""

# %%
"""
## Image Watermarking in Diffusion Models

Now, let's explore a different security aspect: watermarking AI-generated images.
We'll learn to hide information in images generated by Stable Diffusion using frequency-domain manipulation.

<details>
<summary>Vocabulary</summary>

- **Frequency Domain**: Representation of an image in terms of frequencies rather than pixels
- **Fourier Transform**: Algorithm to convert between spatial and frequency domains
- **High/Low Frequencies**: High frequencies represent fine details/edges, low frequencies represent smooth areas

</details>

### Exercise 5.4.1: Setting Up Stable Diffusion

> **Difficulty**: 🔴⚪⚪⚪⚪
> **Importance**: 🔵🔵🔵⚪⚪
>
> You should spend up to ~10 minutes on this exercise.

First, let's set up a small Stable Diffusion model and generate a baseline image.
"""

import torch
from diffusers import StableDiffusionPipeline, UNet2DConditionModel
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from typing import Tuple, Dict, List, Optional, Any, Union


def setup_diffusion_pipeline() -> StableDiffusionPipeline:
    """Set up the Stable Diffusion pipeline."""
    pipe = StableDiffusionPipeline.from_pretrained("nota-ai/bk-sdm-v2-tiny", torch_dtype=torch.float16)

    # Move to appropriate device
    if torch.cuda.is_available():
        pipe = pipe.to("cuda")
    elif torch.backends.mps.is_available():
        pipe = pipe.to("mps")
    else:
        pipe = pipe.to("cpu")

    return pipe


def generate_baseline_image(pipe: StableDiffusionPipeline, prompt: str, seed: int = 8, steps: int = 5) -> Image.Image:
    """
    Generate an image with the sd model.

    Args:
        pipe: Stable Diffusion pipeline
        prompt: Text prompt for generation
        seed: Random seed for reproducibility
        steps: Number of inference steps

    Returns:
        image: Generated PIL image
    """
    if "SOLUTION":
        device = pipe.device.type
        generator = torch.Generator(device=device).manual_seed(seed)
        image = pipe(prompt, num_inference_steps=steps, generator=generator).images[0]
        return image
    else:
        # TODO: Generate an image using the pipeline
        # - Create a generator with the given seed
        #   - generator=torch.Generator(device=device).manual_seed(seed)
        # - Call the pipeline with prompt and parameters
        # - Return the first generated image
        pass

# Set up and test
pipe = setup_diffusion_pipeline()
prompt = "a black vase holding a bouquet of roses"
baseline_image = generate_baseline_image(pipe, prompt)

# Display the baseline image
plt.figure(figsize=(8, 8))
plt.imshow(np.array(baseline_image))
plt.title("Baseline Image (No Watermark)")
plt.axis("off")
plt.show()

# Save for comparison
baseline_image.save("baseline_image.png")

# %%
"""
### Exercise 5.4.2: Implementing Frequency-Domain Watermarking

> **Difficulty**: 🔴🔴🔴🔴⚪
> **Importance**: 🔵🔵🔵🔵🔵
>
> You should spend up to ~20 minutes on this exercise.

Now we'll implement watermarking by modifying the UNet's output in the frequency domain. The idea is to subtly alter specific frequency bands during the diffusion process.

The watermarking process:
1. Hook into the UNet's forward pass
2. Convert intermediate features to frequency domain using FFT
3. Modify specific frequency bands
4. Convert back to spatial domain
"""


class FrequencyWatermarker:
    """Watermarker that modifies specific frequency bands in UNet outputs."""

    def __init__(self) -> None:
        """
        Initialize the watermarker.
        """
        self.hook_handle = None

    def watermark_hook(
        self, module: torch.nn.Module, input: Tuple[torch.Tensor, ...], output: Tuple[torch.Tensor, ...]
    ) -> Tuple[torch.Tensor, ...]:
        """
        Hook function that modifies UNet output in frequency domain.

        This function is called during the forward pass of the UNet.
        """
        if "SOLUTION":
            # Extract the output tensor to modify (second channel)
            to_update = output[0][1].to(dtype=torch.float32)

            # Convert to frequency domain
            fft_output = torch.fft.fft2(to_update)
            fft_shifted = torch.fft.fftshift(fft_output, dim=(-2, -1))

            # Modify specific frequency band
            start, end = (3, 25)
            fft_shifted[:, start:end, :] *= 0.98

            # Convert back to spatial domain
            fft_unshifted = torch.fft.ifftshift(fft_shifted, dim=(-2, -1))
            spatial_output = torch.fft.ifft2(fft_unshifted)

            # Update the output
            output[0][1] = spatial_output.real

            return output
        else:
            # TODO: Implement frequency domain watermarking
            # - Extract the correct tensor from the output
            #   - write an adhoc hook and look at the model outputs to check
            #   - look at the implementation to see what is happening under the hood in the SD pipeline
            #   - ask a TA / check solution to  make sure you are looking at the correct tensor
            # - Apply 2D FFT and shift
            # - Modify frequencies
            #   - to start, just multiply the rectangle [:, 10:30] or similar with 0.98
            #   - You can move to more fancy and less discernible watermarks after you have completed this exercise
            # - Apply inverse FFT and modify the hook output
            pass

    def attach(self, unet: torch.nn.Module) -> None:
        self.hook_handle = unet.register_forward_hook(self.watermark_hook)

    def detach(self) -> None:
        if self.hook_handle:
            self.hook_handle.remove()
            self.hook_handle = None


"""
<details>
<summary>Hint: how to fft</summary>
- torch.fft.fftshift(torch.fft.fft2(...), dim=(-2, -1)) will give you the fft and shift it correctly
- remember to unshift before you calculate the inverse fft
</details>
"""


def generate_watermarked_image(
    pipe: StableDiffusionPipeline, prompt: str, watermarker: FrequencyWatermarker, seed: int = 8, steps: int = 5
) -> Image.Image:
    """Generate an image with watermarking applied."""
    # Extract UNet from pipeline
    unet = pipe.components["unet"]

    # Attach watermarker
    watermarker.attach(unet)

    try:
        # Generate image
        device = pipe.device.type
        generator = torch.Generator(device=device).manual_seed(seed)
        image = pipe(prompt, num_inference_steps=steps, generator=generator).images[0]
    finally:
        # Always detach the watermarker
        watermarker.detach()

    return image


# Test watermarking
watermarker = FrequencyWatermarker()
watermarked_image = generate_watermarked_image(pipe, prompt, watermarker)

# Display comparison
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes[0].imshow(np.array(baseline_image))
axes[0].set_title("Baseline (No Watermark)")
axes[0].axis("off")

axes[1].imshow(np.array(watermarked_image))
axes[1].set_title("Watermarked")
axes[1].axis("off")

plt.tight_layout()
plt.show()

# Save watermarked image
watermarked_image.save("watermarked_image.png")


@report
def test_watermark_hook(solution_watermarker):
    """requires: GPU (mirrors the UNet output layout the hook runs against).

    We exercise the hook on a synthetic UNet output rather than a real forward
    pass. The hook is documented to modify only the second batch element
    (index 1) in a frequency band, so we check:
      1. The first batch element (index 0) is left untouched.
      2. The second batch element is actually changed (the roundtrip through
         FFT -> band scaling -> inverse FFT is not a no-op).
    """
    torch.manual_seed(0)
    # The hook reads/writes output[0][batch_index], so output[0] is a single
    # tensor of shape (batch, channels, H, W); it edits batch element 1.
    fake_tensor = torch.randn(2, 4, 32, 32)
    original = fake_tensor.clone()
    fake_output = (fake_tensor,)

    watermarker = solution_watermarker()
    result = watermarker.watermark_hook(module=None, input=None, output=fake_output)
    modified = result[0]

    # Batch element 0 must be untouched.
    assert torch.allclose(modified[0], original[0], atol=1e-4), (
        "The hook modified batch element 0; it should only touch element 1"
    )
    # Batch element 1 must actually change (watermark applied).
    diff = (modified[1] - original[1]).abs().max().item()
    assert diff > 1e-6, "The hook did not modify batch element 1; the watermark is a no-op"
    print("  All tests passed!")


test_watermark_hook(FrequencyWatermarker)

# %%
"""
### Exercise 5.4.3: Analyzing Watermarks with FFT

> **Difficulty**: 🔴🔴🔴⚪⚪
> **Importance**: 🔵🔵🔵🔵⚪
>
> You should spend up to ~15 minutes on this exercise.

Let's analyze the watermark by examining the frequency domain of both images. The watermark should be visible as modifications in specific frequency bands.
"""


def compute_fft_magnitude_spectrum(image: Union[Image.Image, np.ndarray]) -> Tuple[np.ndarray, np.ndarray]:
    """
    Compute the magnitude spectrum of an image's FFT.

    Args:
        image: PIL Image or numpy array

    Returns:
        magnitude_spectrum: Log magnitude spectrum (in dB)
        fft_shifted: Shifted FFT for further analysis
    """
    if "SOLUTION":
        # Convert to numpy if needed
        if hasattr(image, "size"):  # PIL Image
            image_np = np.array(image)
        else:
            image_np = image

        # Compute 2D FFT
        fft = np.fft.fft2(image_np)
        fft_shifted = np.fft.fftshift(fft)

        # Compute magnitude spectrum in dB
        magnitude_spectrum = 20 * np.log(np.abs(fft_shifted) + 1e-8)

        return magnitude_spectrum, fft_shifted
    else:
        # TODO: Implement FFT magnitude spectrum computation
        # - Convert image to numpy array
        # - Apply 2D FFT and shift
        # - Compute magnitude in dB (20 * log)
        pass


def visualize_frequency_comparison(baseline_image: Image.Image, watermarked_image: Image.Image) -> np.ndarray:
    """Visualize and compare frequency domains of baseline and watermarked images."""
    # Compute FFT for both images
    mag_baseline, fft_baseline = compute_fft_magnitude_spectrum(baseline_image)
    mag_watermarked, fft_watermarked = compute_fft_magnitude_spectrum(watermarked_image)

    # Normalize for visualization
    min_mag = min(mag_baseline.min(), mag_watermarked.min())
    max_mag = max(mag_baseline.max(), mag_watermarked.max())

    mag_baseline_norm = (mag_baseline - min_mag) / (max_mag - min_mag)
    mag_watermarked_norm = (mag_watermarked - min_mag) / (max_mag - min_mag)

    # Create comparison plots
    fig, axes = plt.subplots(1, 3, figsize=(12, 10))

    # Magnitude spectra
    axes[0].imshow(mag_baseline_norm, cmap="gray")
    axes[0].set_title("Baseline - Magnitude Spectrum")
    axes[0].axis("off")

    axes[1].imshow(mag_watermarked_norm, cmap="gray")
    axes[1].set_title("Watermarked - Magnitude Spectrum")
    axes[1].axis("off")

    # Difference heatmap
    magnitude_diff = np.abs(mag_baseline_norm - mag_watermarked_norm)
    magnitude_diff = magnitude_diff / (magnitude_diff.mean() + 1e-8)  # Normalize

    im = axes[2].imshow(magnitude_diff, cmap="hot")
    axes[2].set_title("Difference Heatmap")
    axes[2].axis("off")
    plt.colorbar(im, ax=axes[2], fraction=0.046)

    plt.tight_layout()
    plt.show()

    return magnitude_diff


# Analyze the watermark
print("Analyzing frequency domain differences...")
diff_map = visualize_frequency_comparison(baseline_image, watermarked_image)

# Print statistics
print("\nWatermark Analysis:")
print(f"Maximum difference in frequency domain: {diff_map.max():.4f}")
print(f"Mean difference in frequency domain: {diff_map.mean():.4f}")

# %%
"""
### Exercise 5.4.4: Testing Watermark Robustness

> **Difficulty**: 🔴🔴🔴🔴⚪
> **Importance**: 🔵🔵🔵🔵🔵
>
> You should spend up to ~15 minutes on this exercise.

Let's test how robust our watermark is to common image transformations.
A good watermark should survive compression, resizing, and other modifications.

You can attempt to write the check_watermark_robustness function yourself if you'd like,
but the solution is written below as this exercise isn't very fun, so you can also
just skim through the solution.
"""

from PIL import Image, ImageFilter
import io


def apply_image_transformation(image: Image.Image, transform_type: str, **kwargs: Any) -> Image.Image:
    """
    Apply various transformations to test watermark robustness.

    Args:
        image: PIL Image
        transform_type: One of ['jpeg', 'resize', 'blur', 'noise']
        **kwargs: Additional parameters for the transformation

    Returns:
        transformed_image: Transformed PIL Image
    """
    if transform_type == "jpeg":
        # JPEG compression
        quality = kwargs.get("quality", 50)
        buffer = io.BytesIO()
        image.save(buffer, format="JPEG", quality=quality)
        buffer.seek(0)
        return Image.open(buffer)

    elif transform_type == "resize":
        # Resize down and back up
        scale = kwargs.get("scale", 0.5)
        orig_size = image.size
        small_size = (int(orig_size[0] * scale), int(orig_size[1] * scale))
        return image.resize(small_size, Image.Resampling.LANCZOS).resize(orig_size, Image.Resampling.LANCZOS)

    elif transform_type == "blur":
        # Gaussian blur
        radius = kwargs.get("radius", 2)
        return image.filter(ImageFilter.GaussianBlur(radius=radius))

    elif transform_type == "noise":
        # Add Gaussian noise
        std = kwargs.get("std", 10)
        img_array = np.array(image).astype(float)
        noise = np.random.normal(0, std, img_array.shape)
        noisy = np.clip(img_array + noise, 0, 255).astype(np.uint8)
        return Image.fromarray(noisy)


def check_watermark_robustness(baseline_image: Image.Image, watermarked_image: Image.Image) -> List[Dict[str, Any]]:
    """Test watermark detection after various transformations."""
    transformations = [
        ("jpeg", {"quality": 30}),
        ("resize", {"scale": 0.5}),
        ("blur", {"radius": 2}),
        ("noise", {"std": 15}),
    ]

    results = []

    for transform_type, params in transformations:
        # Apply transformation to both images
        transformed_baseline = apply_image_transformation(baseline_image, transform_type, **params)
        transformed_watermarked = apply_image_transformation(watermarked_image, transform_type, **params)

        # Compute FFT difference
        mag_base, _ = compute_fft_magnitude_spectrum(transformed_baseline)
        mag_water, _ = compute_fft_magnitude_spectrum(transformed_watermarked)

        # Normalize and compute difference
        min_mag = min(mag_base.min(), mag_water.min())
        max_mag = max(mag_base.max(), mag_water.max())
        mag_base_norm = (mag_base - min_mag) / (max_mag - min_mag + 1e-8)
        mag_water_norm = (mag_water - min_mag) / (max_mag - min_mag + 1e-8)

        diff = np.abs(mag_base_norm - mag_water_norm)

        # Measure watermark strength in the target frequency band
        center = np.array(diff.shape) // 2
        y, x = np.ogrid[: diff.shape[0], : diff.shape[1]]

        # Create mask for frequency band 3-25
        dist_from_center = np.sqrt((x - center[1]) ** 2 + (y - center[0]) ** 2)
        band_mask = (dist_from_center >= 3) & (dist_from_center <= 25)

        watermark_strength = diff[band_mask].mean() if band_mask.any() else 0

        results.append(
            {
                "transform": transform_type,
                "params": params,
                "strength": watermark_strength,
                "transformed_image": transformed_watermarked,
            }
        )

    return results


# Test robustness
print("Testing watermark robustness...")
robustness_results = check_watermark_robustness(baseline_image, watermarked_image)

# Visualize results
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes = axes.flatten()

# Original watermarked image
axes[0].imshow(np.array(watermarked_image))
axes[0].set_title("Original Watermarked")
axes[0].axis("off")

# Transformed images
for i, result in enumerate(robustness_results):
    axes[i + 1].imshow(np.array(result["transformed_image"]))
    transform_name = f"{result['transform'].capitalize()}"
    param_str = ", ".join(f"{k}={v}" for k, v in result["params"].items())
    axes[i + 1].set_title(f"{transform_name} ({param_str})\nStrength: {result['strength']:.3f}")
    axes[i + 1].axis("off")

# Hide unused subplot
axes[-1].axis("off")

plt.tight_layout()
plt.show()

# Summary
print("\nRobustness Summary:")
print("=" * 50)
for result in robustness_results:
    print(f"{result['transform'].capitalize()}: strength = {result['strength']:.4f}")
    if result["strength"] > 0.01:
        print("  ✓ Watermark detected")
    else:
        print("  ✗ Watermark lost")


# %%
"""
## Summary and Next Steps

Congratulations! You've completed Day 5. You've learned:

1. **Adversarial Attacks on Vision Models** (Section 1):
   - How to craft targeted adversarial examples
   - The trade-off between attack success and perturbation visibility
   - L2 and L∞ constraints for imperceptible attacks

2. **Adversarial Examples in Language Models** (Section 2):
   - Why prompt attacks are harder in discrete token spaces
   - How GCG uses embedding gradients to rank candidate token replacements

3. **Prefix Tuning in Embedding Space** (Section 3):
   - How prefix tuning can optimize one shared latent prefix across a batch of prompts
   - Why the continuous relaxation is easier to optimize but harder to deploy as text

4. **Image Watermarking** (Section 4):
   - Embedding information in the frequency domain
   - Using forward hooks to modify model behavior
   - Testing watermark robustness

### Extensions to Try:

1. **Advanced Attacks**:
   - Implement PGD (Projected Gradient Descent) attack
   - Try black-box attacks without gradient access
   - Test transferability between different models

2. **Advanced Watermarking**:
   - Implement the actual tree ring watermarking technique from the paper
   - Implement watermark detection methods
   - Try watermarking audio models

3. **Advanced Language-Model Attacks**:
   - Implement the full [LARGO](https://arxiv.org/abs/2505.10838) loop: ask the model to interpret the learned latent
     prefix as natural language, then back-project that text into embedding space and keep iterating
   - Extend the optimization to learn one shared prefix across a batch of harmful prompts (universal prefix)
   - Try prefix tuning on a benign task (e.g. steering the model toward a particular writing style) and compare how
     much easier it is than jailbreak-style objectives

4. **Defenses**:
   - Implement adversarial training
   - Build watermark removal attacks

Ask a TA for papers or help with any of these you'd like to explore further.
"""

# %%
